name: Auto Validate Package and Release

on:
  workflow_dispatch:
    ~
  push:
    branches: [master]
    paths:
      - "src/**"
  pull_request:
    branches: [master]
    paths:
      - "src/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  json-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: json-validate
        id: json-validate
        uses: GrantBirki/json-yaml-validate@v3.3.2 # replace with the latest version
        with:
          comment: "true"
          base_dir: "src"
          exclude_file: "exclude.txt"

  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set build number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Create ZIP archive with build number
        run: |
          cd src
          zip -r "../KumoOTagayasu-build-${BUILD_NUMBER}.mrpack" ./*

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ env.BUILD_NUMBER }}"
          name: "Kumo O Tagayasu Build-${{ env.BUILD_NUMBER }}"
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .mrpack file to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ env.BUILD_NUMBER }}"
          files: "KumoOTagayasu-build-${{ env.BUILD_NUMBER }}.mrpack"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build server
        run: |
          mkdir server
          mv "KumoOTagayasu-build-${BUILD_NUMBER}.mrpack" ./server
          cd server
          wget https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.4.6/forge-1.20.1-47.4.6-installer.jar
          java -jar forge-1.20.1-47.4.6-installer.jar --installServer
          wget https://github.com/nothub/mrpack-install/releases/download/v0.16.10/mrpack-install-linux
          chmod 755 mrpack-install-linux
          ./mrpack-install-linux "KumoOTagayasu-build-${BUILD_NUMBER}.mrpack" --server-dir ./ --server-file ./forge-1.20.1-47.4.6-installer.jar
          rm -f "KumoOTagayasu-build-${BUILD_NUMBER}.mrpack"
          rm -f mrpack-install-linux
          rm -f forge-1.20.1-47.4.6-installer.jar
          rm -f install.log
          zip -r "../Server-KumoOTagayasu-build-${BUILD_NUMBER}.zip" ./*
          
      - name: Upload server file to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ env.BUILD_NUMBER }}"
          files: "Server-KumoOTagayasu-build-${{env.BUILD_NUMBER}}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
